//  Auth - Signup
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//  Auth - Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//  Auth - Logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Skin Products
export const GET_SKIN_PRODUCT = "GET_SKIN_PRODUCT";
export const GET_SKIN_PRODUCT_SUCCESS = "GET_SKIN_PRODUCT_SUCCESS";
export const GET_SKIN_PRODUCT_FAILURE = "GET_SKIN_PRODUCT_FAILURE";

// Hair Products
export const GET_HAIR_PRODUCT = "GET_HAIR_PRODUCT";
export const GET_HAIR_PRODUCT_SUCCESS = "GET_HAIR_PRODUCT_SUCCESS";
export const GET_HAIR_PRODUCT_FAILURE = "GET_HAIR_PRODUCT_FAILURE";

// BathNBody Products
export const GET_BATHNBODY_PRODUCT = "GET_BATHNBODY_PRODUCT";
export const GET_BATHNBODY_PRODUCT_SUCCESS = "GET_BATHNBODY_PRODUCT_SUCCESS";
export const GET_BATHNBODY_PRODUCT_FAILURE = "GET_BATHNBODY_PRODUCT_FAILURE";

// All Products
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

// Single Product
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";



// Cart
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";
export const CART_ITEM_ZERO ='CART_ITEM_ZERO'

export const POST_CART_PRODUCT = "POST_CART_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const INC_CART_QUANTITY = "INC_CART_QUANTITY";
export const DEC_CART_QUANTITY = "DEC_CART_QUANTITY";






// Address
export const POST_USER_ADDRESS = "POST_USER_ADDRESS";
export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const GET_USER_PERSONAL_DETAILS = "GET_USER_PERSONAL_DETAILS";
export const POST_USER_PERSONAL_DETAILS = "POST_USER_PERSONAL_DETAILS";




